#!/bin/bash

# Global variables.
running=1

# Script functions.
update() {
	if [ $1 -eq 1 ]
	then
		apt-get update
		apt-get upgrade
	elif [ $1 -eq 2 ]
	then
		snap refresh 2> /dev/null # If snap packages are updated, it throws an error instead of simple warning output.
	elif [ $1 -eq 3 ]
	then
		apt-get update
		apt-get upgrade
		snap refresh 2> /dev/null
	fi
}

# Program main loop.
while [ $running -eq 1 ]
do

	# User option request.
	echo "Do you want to update only apt(1), only snap(2), both(3) or exit(4)"
	read userOption

	# User option input process.
	case $userOption in
		1) echo "Updating and upgrading APT packages..."
		update 1 > /dev/null # We don't need any output from this commands.
		echo "Updated!"
		break
		;;
		2) echo "Updating and upgrading SNAP packages..."
		update 2 > /dev/null
		echo "Updated!"
		break
		;;
		3) echo "Updating and upgrading APT and SNAP packages..."
		update 3 > /dev/null
		echo "Updated!"
		break
		;;
		4) break
		;;
		*) echo $userOption " is not a valid option!" # Makes 1,2,3,4 the only valid options.
		;;
	esac # End case.
done # End loop.

# Script by ToniCoding.
# Tested on Ubuntu 22.04.
# Working: 100%
